name: yarn-spa-test
description: This GitHub Action will build and test your app
author: johnb8005
branding:
  icon: book-open
  color: purple
inputs:
  build-command:
    description: build command
    default: VITE_VERSION=${GITHUB_REF##*/} VITE_GIT_SHA=$GITHUB_SHA yarn build
  nodeversion:
    description: node version
    default: 18
  message:
    description: The message to prepend the review suggestion
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.nodeversion }}
    - name: Install dependencies via yarn
      run: yarn
      shell: bash
    - name: Test
      run: yarn test
      shell: bash
    - name: Build
      run: ${{ inputs.build-command }}
      shell: bash
